### ISSUE TITLE
git fetch operations do not have a timeout

### ISSUE THREAD

**Issue by rudle** [andrmuel/projectile-git-autofetch#4]
Hello, thanks for writing git-autofetch. It's neat!

If a network connection is severed while emacs is open, a `git fetch` command will be issued for each project known to projectile. This command will never return, and will waste processes on the user's machine.

A cursory look through the man page does not show me a simple --timeout switch, so I don't yet have a recommended patch. Perhaps the tool that issues the command (eg. "shells out") has a global timeout that could be set.

**Comment by rudle** [comment]
My root cause analysis may have been faulty. It may not be necessary for the network to be severed, but rather if git fetch is waiting on user input, such as the passphrase for an ssh key, the symptom will occur. I believe that a global command timeout would address this problem sufficiently.

**Comment by andrmuel** [comment]
Hello

I just looked into this a bit. I can reproduce it by removing ssh keys from the keychain (ssh-add -D).

I think that the git environment variables `GIT_ASKPASS` and `SSH_ASKPASS` might be abused to prevent blocking rather than getting user input. I couldn't get that to work though (I think its ssh asking for a password, rather than git).

A timeout may make more sense, since it should also catch other issues. I have added the branch `process-timeout` to implement this. Please try if that works for you. You'll also need to set `projectile-git-autofetch-timeout` to some reasonable value, as it is disabled by default.

**Comment by andrmuel** [comment]
Haven't heard back from you - merging and closing ...
